networks:
  vision-service-node:
    name: vision-service-node-${STACK_IDENTIFIER}-${INSTANCE-1}
    driver: overlay
    attachable: true

services:
  app:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    image: ${DOCKER_REGISTRY-visionweb3foundation}/service-node-app:${DOCKER_TAG-local}
    build:
      context: .
      dockerfile: Dockerfile
      target: servicenode
      x-bake:
        tags:
          - ${DOCKER_REGISTRY-visionweb3foundation}/service-node-app:${DOCKER_TAG-local}
          - ${DOCKER_REGISTRY-visionweb3foundation}/service-node-app:${EXTRA_TAG-local}
    networks:
      vision-service-node:
    env_file: []
    environment:
      # Ignore the env file inside the docker container
      VISION_ENV_FILE: ' '
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      APP_LOG_FILE_ENABLED: 'false'
      APP_LOG_FORMAT: human_readable
      DB_URL: postgresql+psycopg://vision-service-node:vision@db/vision-service-node
      CELERY_BROKER: amqp://vision-service-node:vision@broker:5672/vision-service-node
      CELERY_BACKEND: db+postgresql+psycopg://vision-service-node:vision@db/vision-service-node-celery
      DEV_MODE: ${DEV_MODE}
    ports:
      - 808${INSTANCE-0}:8080
    healthcheck:
      test: ["CMD", "/usr/bin/vision-service-node-server", "--status"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./vision
          target: /opt/vision/vision-service-node/lib/python3/site-packages/vision
        - action: sync+restart
          path: ./linux/scripts/start-web.py
          target: /opt/vision/vision-service-node/bin/start-web.py
        - action: sync+restart
          path: ./linux/scripts/vision-service-node-server
          target: /opt/vision/vision-service-node/bin/vision-service-node-server
        - action: sync+restart
          path: service-node-config.yml
          target: /opt/vision/vision-service-node/service-node-config.yml
        - action: sync+restart
          path: alembic.ini
          target: /opt/vision/vision-service-node/alembic.ini
        - action: sync+restart
          path: service-node-config.env
          target: /etc/vision/service-node-config.env
        - action: sync+restart
          path: bids.yml
          target: /etc/vision/service-node-bids.yml
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: debian
        - action: rebuild
          path: configurator
        - action: rebuild
          path: linux/etc
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: poetry.lock

  worker:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    image: ${DOCKER_REGISTRY-visionweb3foundation}/service-node-worker:${DOCKER_TAG-local}
    build:
      context: .
      dockerfile: Dockerfile
      target: servicenode-celery-worker
      x-bake:
        tags:
          - ${DOCKER_REGISTRY-visionweb3foundation}/service-node-worker:${DOCKER_TAG-local}
          - ${DOCKER_REGISTRY-visionweb3foundation}/service-node-worker:${EXTRA_TAG-local}
    networks:
      vision-service-node:
    env_file: []
    environment:
      # Ignore the env file inside the docker container
      VISION_ENV_FILE: ' '
      VISION_CELERY_AUTORESTART: 'true'
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      CELERY_LOG_FORMAT: human_readable
      CELERY_LOG_FILE_ENABLED: 'false'
      DB_URL: postgresql+psycopg://vision-service-node:vision@db/vision-service-node
      CELERY_BROKER: amqp://vision-service-node:vision@broker:5672/vision-service-node
      CELERY_BACKEND: db+postgresql+psycopg://vision-service-node:vision@db/vision-service-node-celery
      DEV_MODE: ${DEV_MODE}
    healthcheck:
      test: ["CMD", "/usr/bin/vision-service-node-celery", "--status"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      # Wait for the app to setup the DB
      app:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./vision
          target: /opt/vision/vision-service-node/lib/python3/site-packages/vision
        - action: sync+restart
          path: ./linux/scripts/vision-service-node-celery
          target: /opt/vision/vision-service-node/bin/vision-service-node-celery
        - action: sync+restart
          path: service-node-config.yml
          target: /opt/vision/vision-service-node/service-node-config.yml
        - action: sync+restart
          path: alembic.ini
          target: /opt/vision/vision-service-node/alembic.ini
        - action: sync+restart
          path: service-node-config.env
          target: /etc/vision/service-node-config.env
        - action: sync+restart
          path: bids.yml
          target: /etc/vision/service-node-bids.yml
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: debian
        - action: rebuild
          path: configurator
        - action: rebuild
          path: linux/etc
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: poetry.lock

  db:
    image: postgres:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      vision-service-node:
    # ports:
    #   - 5432:5432 # for alembic
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresql_data:/postgresql_data
      - type: bind
        source: ./db_init.sh
        target: /docker-entrypoint-initdb.d/init-user-db.sh
        read_only: true
    develop:
      watch:
        - action: rebuild
          path: db_init.sh

  broker:
    image: rabbitmq:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    hostname: vision-service-node
    networks:
      vision-service-node:
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: vision-service-node
      RABBITMQ_DEFAULT_PASS: vision
      RABBITMQ_DEFAULT_VHOST: vision-service-node
    volumes:
      - rabbitmq_data:/rabbitmq_data

volumes:
  postgresql_data:
  rabbitmq_data:
