[tool.poetry]
name = "vision-service-node"
version = "0.1.0"
description = "Vision Service Node (reference implementation)"
authors = ["Vision GmbH <contact@vision.io>"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    { include = "vision"}
]

[tool.setuptools.packages.find]
where = ["."]
include = ["vision"]
namespaces = true

[tool.poetry.group.test.dependencies]
pytest = "8.3.4"
pytest-cov = "6.0.0"
pytest-mock = "3.14.0"
eth-tester = "0.12.1b1"
web3 = {extras = ["tester"], version = "7.10.0"}

[tool.poetry.group.lint.dependencies]
bandit = "1.8.2"
flake8 = "7.1.1"
isort = "6.0.0"
mypy = "1.0.1"
types-pyyaml = "6.0.12.20241230"
types-requests = "^2.32.0.20240622"
types-sqlalchemy = "^1.4.53.38"
yapf = "0.43.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "4.1.0"


[tool.poetry.group.docs.dependencies]
apispec = "^6.7.1"
apispec-webframeworks = "^1.2.0"
flasgger = "^0.9.7.1"

[tool.poetry.dependencies]
python = "^3.13"
vision-common = "0.3.1"
alembic = "1.14.1"
celery = "5.3.1"
Cerberus = "1.3.4"
Flask = "3.1.0"
Flask-Cors = "5.0.0"
Flask-RESTful = "0.3.10"
marshmallow = "3.26.1"
psycopg = {extras = ["binary", "pool"], version = "3.2.4"}
PyYAML = "6.0.1"
SQLAlchemy = "2.0.37"
web3 = "7.10.0"
JSON-log-formatter = "0.5.2"
pyaml-env = "1.2.1"
python-dotenv = "1.0.1"
hexbytes = "1.2.1"
semantic-version = "2.10.0"
gunicorn = ">=22,<24"
requests = "^2.32.3"
flower = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
