"""Add Node Health table

Revision ID: 2bed90cdde5e
Revises: 5e552e0ec844
Create Date: 2025-03-04 15:10:40.634886

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bed90cdde5e'
down_revision = '5e552e0ec844'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'nodes_health', sa.Column('blockchain_id', sa.Integer(),
                                  nullable=False),
        sa.Column('unhealthy_total', sa.Integer(), nullable=False),
        sa.Column('unhealthy_endpoints', sa.JSON(), nullable=False),
        sa.Column('healthy_total', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['blockchain_id'],
            ['blockchains.id'],
        ), sa.PrimaryKeyConstraint('blockchain_id'))
    op.alter_column('transfers', 'created',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfers', 'created',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(), existing_nullable=False)
    op.drop_table('nodes_health')
    # ### end Alembic commands ###
