"""add new transactions tables

Revision ID: daf1343d36d8
Revises: 2bed90cdde5e
Create Date: 2025-03-11 19:04:48.633477

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'daf1343d36d8'
down_revision = '2bed90cdde5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'transactions', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('blockchain_type', sa.Integer(), nullable=False),
        sa.Column('tx_id', sa.Text(), nullable=False),
        sa.Column('block_number', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('status_id', sa.Integer(), nullable=False),
        sa.Column('fee', sa.Integer(), nullable=False),
        sa.Column('raw_data', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ['blockchain_type'],
            ['blockchain_types.id'],
        ), sa.ForeignKeyConstraint(
            ['status_id'],
            ['transfer_status.id'],
        ), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('tx_id'))
    op.create_table(
        'evm_transactions',
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('from_address', sa.Text(), nullable=False),
        sa.Column('to_address', sa.Text(), nullable=True),
        sa.Column('value', sa.Integer(), nullable=False),
        sa.Column('nonce', sa.BigInteger(), nullable=True),
        sa.Column('input_data', sa.Text(), nullable=True),
        sa.Column('chain_id', sa.Integer(), nullable=False),
        sa.Column('max_fee_per_gas', sa.Integer(), nullable=False),
        sa.Column('max_priority_fee_per_gas', sa.Integer(),
                    nullable=True),
        sa.Column('gas_limit', sa.Integer(), nullable=False),
        sa.Column('signature', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['transaction_id'],
            ['transactions.id'],
        ), sa.PrimaryKeyConstraint('transaction_id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evm_transactions')
    op.drop_table('transactions')
    op.drop_table('blockchain_types')
    # ### end Alembic commands ###
